### ISSUE TITLE
Unoblivious enlarge operation

### ISSUE THREAD

**Issue by AKarbas** [kudelskisecurity/oramfs#1]
When an ORAM is enlarged, the distribution of the blocks is no longer indistinguishable as the data are put in even leaves. They should be remapped uniformly. See [these lines](https://github.com/kudelskisecurity/oramfs/blob/de19fca0c13d5715d05af289128fb8e01b7bbff2/src/manage.rs#L590).

**Comment by amietn** [comment]
Thank you for reporting this issue. I have pushed a commit to mitigate this. Let me know if you think this is still a problem.

See https://github.com/kudelskisecurity/oramfs/commit/fe3cb8b6f387086cdad8d9e7e85bcb84e5252919

**Comment by tgkudelski** [comment]
Thank you @AKarbas

**Comment by tgkudelski** [comment]
Just to expand on this, we patched it by mapping old branches of the tree either on the left or right leaf of the new layer at random. So it's not a complete shuffle of the position map, but it seems to us that it should work well enough for security (and it's definitely faster and cleaner).

**Comment by AKarbas** [comment]
LGTM.

A complete reshuffle can be proved secure a bit more cleanly, but this is enough as well.
